# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3ea5785d4f0b91833d5a7fcbd3110960165186b12de28db79bbc30b54f1c172eeb60b944155641fe63fefc425e30dead19f9c0bfef5cf34dd93acef857f26ec

test:
  secret_key_base: 1170193e26159bfb0292ad05e21862afd905730e0f5f03e8df7c4eabb50ddbe880978696515be0b2750d4a6cf4b944b7be8ec67962be6933240d9a944fc2ebbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
